import { defineConfig, devices } from '@playwright/test';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({
  path: path.resolve(__dirname, 'config/.env.test.local'),
  override: false,
});

/**
 * Which environment this run targets. The package.json scripts export
 * PLAYWRIGHT_PROJECT_NAME alongside `--project`, and the webServer below needs
 * it to pick the demo's env file — `--project` alone is not visible here.
 */
const demoEnvironment = (() => {
  const project = process.env.PLAYWRIGHT_PROJECT_NAME || '';
  if (project.includes('prod')) return 'prod';
  if (project.includes('stage')) return 'stage';
  return 'local';
})();

export default defineConfig({
  testDir: './e2e/playwright/tests',
  timeout: 60_000,
  expect: { timeout: 10_000 },
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [
    ['html', { outputFolder: 'test-reports/playwright-report' }],
    ['json', { outputFile: 'test-reports/playwright-results.json' }],
    ['list'],
  ],
  use: {
    // Hard-coded :3010 so `npm run test:e2e` runs without any env override.
    // :3000 is reserved for `next dev` (developer-facing demo start), :3001 is
    // bridge-svelte's test harness. :3010 keeps the bridge-nextjs test harness
    // isolated from both. LOCAL_BASE_URL is still respected as an escape hatch.
    baseURL: process.env.LOCAL_BASE_URL || 'http://localhost:3010',
    trace: process.env.PLAYWRIGHT_RECORD_ALL === 'true' ? 'on' : 'retain-on-failure',
    screenshot: process.env.PLAYWRIGHT_RECORD_ALL === 'true' ? 'on' : 'only-on-failure',
    headless: process.env.PLAYWRIGHT_HEADED !== 'true',
    // Seeds `localStorage['bridge:appId']` — written by global-setup, which
    // resolves the app id from the test-data API (TBP-721).
    storageState: path.resolve(__dirname, 'e2e/playwright/.auth/base-state.json'),
  },
  projects: [
    { name: 'local', use: { ...devices['Desktop Chrome'] } },
    { name: 'local-no-auth', use: { ...devices['Desktop Chrome'] } },
    { name: 'stage', use: { ...devices['Desktop Chrome'] } },
    { name: 'prod', use: { ...devices['Desktop Chrome'] } },
  ],
  outputDir: 'test-reports/test-results',
  webServer: {
    // All env files live in `bridge-nextjs/config/`. The demo env file is picked
    // by ENVIRONMENT: `config/.env.demo.test.<local|stage|prod>`. It used to be
    // hard-coded to `.env.demo.test.local`, so `test:e2e:stage` provisioned test
    // accounts on stage while the browser drove the LOCAL bridge-api with the
    // local app id — every authenticated stage spec was measuring the wrong
    // backend (TBP-721). global-setup now asserts the demo's environment and
    // API root against the project, so that cannot recur silently.
    //
    // `local` is generated by pre-setup (its API root depends on the slot);
    // `stage` and `prod` are tracked in git with every key explicit.
    // `dotenv-cli` injects the file into process.env before `next dev` runs, so
    // the demo never depends on any file in its own directory — keeping the
    // developer's `config/.env.local` (their own appId for `npm run dev`)
    // cleanly separated from test runs.
    //
    // Use the demo-local Next binary (15.2.4, webpack dev) explicitly. The
    // workspace root hoists a newer Next (16.x) whose `next dev` defaults to
    // Turbopack, which panics on the edge middleware bundle
    // (incrementalCacheHandler invariant). `./node_modules/.bin/next` pins the
    // demo's own webpack-based compiler and sidesteps that panic.
    command: `cd demo && dotenv -e ../config/.env.demo.test.${demoEnvironment} -- ./node_modules/.bin/next dev -p 3010`,
    url: 'http://localhost:3010',
    reuseExistingServer: !process.env.CI,
    timeout: 60_000,
  },
  globalSetup: require.resolve('./e2e/playwright/global-setup'),
});
